### ISSUE TITLE
git apply patch failed

### ISSUE THREAD

**Issue by dotku** [mobxjs/create-react-app-mobx#3]
git apply introduce-mobx.patch
error: patch failed: package.json:6
error: package.json: patch does not apply
error: patch failed: src/App.js:1
error: src/App.js: patch does not apply
error: src/Counter.js: already exists in working directory
error: patch failed: src/index.js:1
error: src/index.js: patch does not apply

**Comment by mweststrate** [comment]
There is no reason anymore for this repo to exist. Nowadays tools like https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-mobx can be used instead.
